name: Build-scan-publish container

on:
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ${{ github.repository }}
  CACHE_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/docker_zad1-cache
  SCAN_IMAGE: docker_zad1_scan:latest   # tymczasowa nazwa do skanu

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub (cache)
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & load image for scan
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker_zad1/Dockerfile
          platforms: linux/amd64
          load: true                # załaduj do lokalnego dockera
          push: false
          cache-from: type=registry,ref=docker.io/${{ env.CACHE_REPO }}
          cache-to:   type=registry,ref=docker.io/${{ env.CACHE_REPO }},mode=max
          tags: ${{ env.SCAN_IMAGE }}

      - name: Scan built image (Trivy)
        uses: aquasecurity/trivy-action@0.18.0
        with:
          scan-type: image
          image-ref: ${{ env.SCAN_IMAGE }}
          severity: CRITICAL,HIGH
          exit-code: 1
          format: table

  push-image:
    needs: build-and-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub (cache)
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=push,enable=true
            type=sha,format=short
            type=semver,pattern={{version}}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}

      - name: Build & push multi-arch
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker_zad1/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=docker.io/${{ env.CACHE_REPO }}
          cache-to:   type=registry,ref=docker.io/${{ env.CACHE_REPO }},mode=max
