name: Build-scan-publish container

on:
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ${{ github.repository }}
  CACHE_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/docker_zad1-cache

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3

    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch,enable=true
          type=sha,format=short
          type=semver,pattern={{version}}        # jeśli puszujemy tag vX.Y.Z
        labels: |
          org.opencontainers.image.source=${{ github.repositoryUrl }}

    - id: build-test
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./docker_zad1/Dockerfile
        platforms: linux/amd64,linux/arm64
        load: false
        push: false
        outputs: type=oci,dest=/tmp/image.tar
        provenance: false
        cache-from: type=registry,ref=docker.io/${{ env.CACHE_REPO }}
        cache-to:   type=registry,ref=docker.io/${{ env.CACHE_REPO }},mode=max 
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Scan built image (Trivy)
      uses: aquasecurity/trivy-action@0.18.0 
      with:
        input: /tmp/image.tar
        severity: CRITICAL,HIGH
        exit-code: 1 
        format: table

  push-image:
    needs: build-and-scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3

    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ env.IMAGE_NAME }}
        tags: |
          type=sha,format=short
          type=ref,event=branch
          type=semver,pattern={{version}}
        labels: |
          org.opencontainers.image.source=${{ github.repositoryUrl }}

    - uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=docker.io/${{ env.CACHE_REPO }}
        cache-to:   type=registry,ref=docker.io/${{ env.CACHE_REPO }},mode=max
